# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.meas_rep_ue_notification_nr_bncs import MeasRepUeNotificationNrBNCs  # noqa: F401,E501
from swagger_server.models.meas_rep_ue_notification_nr_scs import MeasRepUeNotificationNrSCs  # noqa: F401,E501
from swagger_server import util


class MeasRepUeNotificationNewRadioMeasInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nr_bncs: MeasRepUeNotificationNrBNCs=None, nr_carrier_freq: int=None, nr_scs: MeasRepUeNotificationNrSCs=None):  # noqa: E501
        """MeasRepUeNotificationNewRadioMeasInfo - a model defined in Swagger

        :param nr_bncs: The nr_bncs of this MeasRepUeNotificationNewRadioMeasInfo.  # noqa: E501
        :type nr_bncs: MeasRepUeNotificationNrBNCs
        :param nr_carrier_freq: The nr_carrier_freq of this MeasRepUeNotificationNewRadioMeasInfo.  # noqa: E501
        :type nr_carrier_freq: int
        :param nr_scs: The nr_scs of this MeasRepUeNotificationNewRadioMeasInfo.  # noqa: E501
        :type nr_scs: MeasRepUeNotificationNrSCs
        """
        self.swagger_types = {
            'nr_bncs': MeasRepUeNotificationNrBNCs,
            'nr_carrier_freq': int,
            'nr_scs': MeasRepUeNotificationNrSCs
        }

        self.attribute_map = {
            'nr_bncs': 'nrBNCs',
            'nr_carrier_freq': 'nrCarrierFreq',
            'nr_scs': 'nrSCs'
        }
        self._nr_bncs = nr_bncs
        self._nr_carrier_freq = nr_carrier_freq
        self._nr_scs = nr_scs

    @classmethod
    def from_dict(cls, dikt) -> 'MeasRepUeNotificationNewRadioMeasInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MeasRepUeNotification_newRadioMeasInfo of this MeasRepUeNotificationNewRadioMeasInfo.  # noqa: E501
        :rtype: MeasRepUeNotificationNewRadioMeasInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nr_bncs(self) -> MeasRepUeNotificationNrBNCs:
        """Gets the nr_bncs of this MeasRepUeNotificationNewRadioMeasInfo.


        :return: The nr_bncs of this MeasRepUeNotificationNewRadioMeasInfo.
        :rtype: MeasRepUeNotificationNrBNCs
        """
        return self._nr_bncs

    @nr_bncs.setter
    def nr_bncs(self, nr_bncs: MeasRepUeNotificationNrBNCs):
        """Sets the nr_bncs of this MeasRepUeNotificationNewRadioMeasInfo.


        :param nr_bncs: The nr_bncs of this MeasRepUeNotificationNewRadioMeasInfo.
        :type nr_bncs: MeasRepUeNotificationNrBNCs
        """

        self._nr_bncs = nr_bncs

    @property
    def nr_carrier_freq(self) -> int:
        """Gets the nr_carrier_freq of this MeasRepUeNotificationNewRadioMeasInfo.

        ARFCN applicable for a downlink, uplink or bi-directional (TDD) NR carrier frequency, as defined in ETSI TS 138.101 [i.15].  # noqa: E501

        :return: The nr_carrier_freq of this MeasRepUeNotificationNewRadioMeasInfo.
        :rtype: int
        """
        return self._nr_carrier_freq

    @nr_carrier_freq.setter
    def nr_carrier_freq(self, nr_carrier_freq: int):
        """Sets the nr_carrier_freq of this MeasRepUeNotificationNewRadioMeasInfo.

        ARFCN applicable for a downlink, uplink or bi-directional (TDD) NR carrier frequency, as defined in ETSI TS 138.101 [i.15].  # noqa: E501

        :param nr_carrier_freq: The nr_carrier_freq of this MeasRepUeNotificationNewRadioMeasInfo.
        :type nr_carrier_freq: int
        """

        self._nr_carrier_freq = nr_carrier_freq

    @property
    def nr_scs(self) -> MeasRepUeNotificationNrSCs:
        """Gets the nr_scs of this MeasRepUeNotificationNewRadioMeasInfo.


        :return: The nr_scs of this MeasRepUeNotificationNewRadioMeasInfo.
        :rtype: MeasRepUeNotificationNrSCs
        """
        return self._nr_scs

    @nr_scs.setter
    def nr_scs(self, nr_scs: MeasRepUeNotificationNrSCs):
        """Sets the nr_scs of this MeasRepUeNotificationNewRadioMeasInfo.


        :param nr_scs: The nr_scs of this MeasRepUeNotificationNewRadioMeasInfo.
        :type nr_scs: MeasRepUeNotificationNrSCs
        """

        self._nr_scs = nr_scs
