Y''[Documentation]   robot --outputdir ../../../outputs ./V2XInformationService.robot
...    Test Suite to validate V2X Information Service API (VIS) operations.

*** Settings ***
Resource    environment/variables.txt
Resource    ../../../pics.txt
Resource    ../../../GenericKeywords.robot
Library     REST    ${SCHEMA}://${HOST}:${PORT}    ssl_verify=false
Library     OperatingSystem
Library    JSONLibrary

*** Test Cases ***
TC_MEC_MEC048_MEO_CSE_001_OK
    [Documentation]    TP_MEC_MEC048_MEO_CSE_001_OK
    ...    Check that the IUT responds with a list of all available tenantInfo when requested to a CSE - No query parameters
    ...    ETSI GS MEC 048 v3.1.1, clause 7.3.3.1
    ...    ETSI GS MEC 048 v3.1.1, clause 6.2.2 (TenantInfo)
    [Tags]    PIC_SERVICES
    [Setup]   Register mutiple tenant Info and get tenant Ids   TenantInfo    TenantInfo2    TenantInfo3
    Retrieve all tenant Info resources
    Check HTTP Response Status Code Is    200
    Check HTTP Response Body Json Schema Is  TenantInfoList
    [Teardown]  Remove mutiple tenant Info    ${TENANT_ID_1}    ${TENANT_ID_2}    ${TENANT_ID_3}

TC_MEC_MEC048_MEO_CSE_001_OK_02
    [Documentation]    TP_MEC_MEC048_MEO_CSE_001_OK_02
    ...    Check that the IUT responds with a list of tenantInfo when queried with customerId as query parameter
    ...    ETSI GS MEC 048 v3.1.1, clause 7.3.3.1
    ...    ETSI GS MEC 048 v3.1.1, clause 6.2.2 (TenantInfo)
    [Tags]    PIC_SERVICES
    [Setup]   Register mutiple tenant Info and get tenant Ids   TenantInfo    TenantInfo2    TenantInfo3
    Retrieve all tenant info resources with query parameters    customerId=${CUSTOMER_ID_1}
    Check HTTP Response Status Code Is    200
    Check HTTP Response Body Json Schema Is  TenantInfoList
    FOR  ${tenant}  IN  @{response['body']}
      Should Be Equal As Strings    ${tenant}[tenantId]      ${TENANT_ID_1}
    END
    [Teardown]  Remove mutiple tenant Info    ${TENANT_ID_1}    ${TENANT_ID_2}    ${TENANT_ID_3}

TC_MEC_MEC048_MEO_CSE_001_OK_03
    [Documentation]    TP_MEC_MEC048_MEO_CSE_001_OK_03
    ...    Check that the IUT responds with a list of tenantInfo when queried with customerName as query parameter
    ...    ETSI GS MEC 048 v3.1.1, clause 7.3.3.1
    ...    ETSI GS MEC 048 v3.1.1, clause 6.2.2 (TenantInfo)
    [Tags]    PIC_SERVICES
    [Setup]   Register mutiple tenant Info and get tenant Ids   TenantInfo    TenantInfo2    TenantInfo3
    Retrieve all tenant info resources with query parameters    customerName=${CUSTOMER_NAME_1}
    Check HTTP Response Status Code Is    200
    Check HTTP Response Body Json Schema Is  TenantInfoList
    FOR  ${tenant}  IN  @{response['body']}
      Should Be Equal As Strings    ${tenant}[customerName]      ${CUSTOMER_NAME_1}
    END
    [Teardown]  Remove mutiple tenant Info    ${TENANT_ID_1}    ${TENANT_ID_2}    ${TENANT_ID_3}

TC_MEC_MEC048_MEO_CSE_002_OK
    [Documentation]    TP_MEC_MEC048_MEO_CSE_002_OK
    ...    Check that the IUT creates a new tenantInfo when requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.3.3.4
    ...    ETSI GS MEC 048 v3.1.1, clause 6.2.2 (TenantInfo)
    [Tags]    PIC_SERVICES
    ##No test setup needed because the tenantId is generated by IUT
    Register Tenant Info    TenantInfo
    Check HTTP Response Status Code Is    201
    Check HTTP Response Body Json Schema Is  TenantInfo  
    ${CUSTOMER_ID_VALUE}   Get value entry from JSON file    TenantInfo  customerId
    ${TENANT_NAME_VALUE}   Get value entry from JSON file    TenantInfo  tenantName

    Should Be Equal As Strings    ${response['body']['customerId']}       ${CUSTOMER_ID_VALUE}
    Should Be Equal As Strings    ${response['body']['tenantName']}       ${TENANT_NAME_VALUE}

    [Teardown]  Remove specific tenant info resource    ${TENANT_ID_1}  

TC_MEC_MEC048_MEO_CSE_002_BR
    [Documentation]    TP_MEC_MEC048_MEO_CSE_002_BR
    ...    Check that the IUT responds with an error on creating a tenantInfo with both resourceUseInfo and siteList
    ...    ETSI GS MEC 048 v3.1.1, clause 7.3.3.4 and 6.2.2 (TenantInfo)
    [Tags]    PIC_SERVICES
    Register Tenant Info    TenantInfoBR
    Check HTTP Response Status Code Is    400

TC_MEC_MEC048_MEO_CSE_003_OK
    [Documentation]    TP_MEC_MEC048_MEO_CSE_003_OK
    ...    Check that the IUT responds with a specific tenantInfo when requested to a MEC Consumer
    ...    ETSI GS MEC 048 v3.1.1, clause 7.3.3.1 and 6.2.2 (TenantInfo)
    [Tags]    PIC_SERVICES
    [Setup]   Register Tenant Info    TenantInfo
    Retrieve specific tenant info resource   ${TENANT_ID_1} 
    Check HTTP Response Status Code Is    200
    Check HTTP Response Body Json Schema Is  TenantInfo
    [Teardown]  Remove specific tenant info resource    ${TENANT_ID_1}

TC_MEC_MEC048_MEO_CSE_003_NF
    [Documentation]    TP_MEC_MEC048_MEO_CSE_003_NF
    ...    Check that the IUT returns an error when requesting a non-existing tenantInfo to a MEC Consumer
    ...    ETSI GS MEC 048 v3.1.1, clause 7.4.3.1 and 6.2.2
    [Tags]    PIC_SERVICES
    Retrieve specific tenant info resource    ${NOT_EXISTING_TENANT_ID} 
    Check HTTP Response Status Code Is    404

TC_MEC_MEC048_MEO_CSE_004_OK
    [Documentation]    TP_MEC_MEC048_MEO_CSE_004_OK
    ...    Check that the IUT updates an existing tenantInfo when requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.4.3.5 and 6.2.2
    [Tags]    PIC_SERVICES
    [Setup]   Register tenant Info    TenantInfo
    Update tenant Info    ${TENANT_ID_1}    TenantInfoUpdate
    Check HTTP Response Status Code Is    200
    Check HTTP Response Body Json Schema Is  TenantInfo
    ${CUSTOMER_ID_VALUE}   Get value entry from JSON file    TenantInfoUpdate  customerId
    ${TENANT_NAME_VALUE}   Get value entry from JSON file    TenantInfoUpdate  tenantName
    ${CUSTOMER_NAME_VALUE}   Get value entry from JSON file    TenantInfoUpdate  customerName

    Should Be Equal As Strings    ${response['body']['customerId']}       ${CUSTOMER_ID_VALUE}
    Should Be Equal As Strings    ${response['body']['tenantName']}       ${TENANT_NAME_VALUE}
    Should Be Equal As Strings    ${response['body']['customerName']}       ${CUSTOMER_NAME_VALUE}

    [Teardown]  Remove specific tenant info resource    ${TENANT_ID_1}

TC_MEC_MEC048_MEO_CSE_004_NF
    [Documentation]    TP_MEC_MEC048_MEO_CSE_004_NF
    ...    Check that the IUT returns an error on updating a not existing tenantInfo requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.4.3.5 and 6.2.2
    [Tags]    PIC_SERVICES
    Update tenant Info    ${NOT_EXISTING_TENANT_ID}    TenantInfoUpdate
    Check HTTP Response Status Code Is    404

TC_MEC_MEC048_MEO_CSE_004_BR
    [Documentation]    TP_MEC_MEC048_MEO_CSE_004_BR
    ...    Check that the IUT returns an error on updating with invalid values tenantInfo requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.4.3.2 and 6.2.2
    [Setup]   Register tenant Info    TenantInfo
    Update tenant Info    ${TENANT_ID_1}    TenantInfoBR
    Check HTTP Response Status Code Is    400
    [Teardown]  Remove specific tenant info resource    ${TENANT_ID_1}

TC_MEC_MEC048_MEO_CSE_005_OK
    [Documentation]    TP_MEC_MEC048_MEO_CSE_005_OK
    ...    Check that the IUT removes a tenantInfo when requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.4.3.5
    [Tags]    PIC_SERVICES
    [Setup]   Register tenant Info    TenantInfo
    Remove specific tenant info resource  ${TENANT_ID_1}  
    Check HTTP Response Status Code Is    204

TC_MEC_MEC048_MEO_CSE_005_NF
    [Documentation]    TP_MEC_MEC048_MEO_CSE_005_NF
    ...    Check that the IUT returns an error on deleting a not existing tenantInfo when requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.4.3.5
    [Tags]    PIC_SERVICES
    Remove specific tenant info resource  ${NOT_EXISTING_TENANT_ID}  
    Check HTTP Response Status Code Is    404 

TC_MEC_MEC048_MEO_CSE_006_OK
    [Documentation]    TP_MEC_MEC048_MEO_CSE_006_OK
    ...    Check that the IUT returns a resourceQuotaInfo for a specific tenant when requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.5.3.1, clause 6.2.3
    [Tags]    PIC_SERVICES
    [Setup]   Register tenant Info    TenantInfo
    Register resource quota Info    ${TENANT_ID_1}    ResourceQuotaInfo
    Retrieve specific resource quota info resource   ${TENANT_ID_1} 
    Check HTTP Response Status Code Is    200
    Check HTTP Response Body Json Schema Is  ResourceQuotaInfo
    Remove specific resource quota info resource    ${TENANT_ID_1}
    [Teardown]  Remove specific tenant info resource    ${TENANT_ID_1}

TC_MEC_MEC048_MEO_CSE_006_NF
    [Documentation]    TP_MEC_MEC048_MEO_CSE_006_NF
    ...    Check that the IUT returns an error on retrieving resourceQuotaInfo for a not existing tenant when requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.5.3.1, clause 6.2.3
    [Tags]    PIC_SERVICES
    Retrieve specific resource quota info resource   ${NOT_EXISTING_TENANT_ID} 
    Check HTTP Response Status Code Is    404

# TO DO
TC_MEC_MEC048_MEO_CSE_007_OK
    [Documentation]    TP_MEC_MEC048_MEO_CSE_007_OK
    ...    Check that the IUT updates the resourceQuotaInfo for an existing tenant when requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.5.3.2, clause 6.2.3
    [Tags]    PIC_SERVICES
    [Setup]   Register tenant Info    TenantInfo
    Register resource quota Info    ${TENANT_ID_1}    ResourceQuotaInfo
    Update resource quota Info   ${TENANT_ID_1}    ResourceQuotaInfoUpdate
    Check HTTP Response Status Code Is    200
    Check HTTP Response Body Json Schema Is  ResourceQuotaInfo

    ${CPU_QUOTA_VALUE}   Get value entry from JSON file    ResourceQuotaInfoUpdate  cpuQuota
    ${MEMORY_QUOTA_VALUE}   Get value entry from JSON file    ResourceQuotaInfoUpdate  memoryQuota
    ${DISK_QUOTA_VALUE}   Get value entry from JSON file    ResourceQuotaInfoUpdate  diskQuota

    Should Be Equal As Strings    ${response['body']['cpuQuota']}       ${CPU_QUOTA_VALUE}
    Should Be Equal As Strings    ${response['body']['memoryQuota']}       ${MEMORY_QUOTA_VALUE}
    Should Be Equal As Strings    ${response['body']['diskQuota']}       ${DISK_QUOTA_VALUE}

    Remove specific resource quota info resource    ${TENANT_ID_1}
    [Teardown]  Remove specific tenant info resource    ${TENANT_ID_1}

# TO DO
TC_MEC_MEC048_MEO_CSE_007_NF
    [Documentation]    TP_MEC_MEC048_MEO_CSE_007_NF
    ...    Check that the IUT returns an error on updating the resourceQuotaInfo for a not existing tenant when requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.5.3.2, clause 6.2.3
    [Tags]    PIC_SERVICES
    Update resource quota Info   ${NOT_EXISTING_TENANT_ID}    ResourceQuotaInfoUpdate
    Check HTTP Response Status Code Is    404
TC_MEC_MEC048_MEO_CSE_008_OK
    [Documentation]    TP_MEC_MEC048_MEO_CSE_008_OK
    ...    Check that the IUT creates the resourceQuotaInfo for an existing tenant when requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.5.3.4, clause 6.2.3
    [Tags]    PIC_SERVICES
    [Setup]   Register tenant Info    TenantInfo
    Register resource quota Info    ${TENANT_ID_1}    ResourceQuotaInfo
    Check HTTP Response Status Code Is    201
    Check HTTP Response Body Json Schema Is  ResourceQuotaInfo
    Remove specific resource quota info resource    ${TENANT_ID_1}
    [Teardown]  Remove specific tenant info resource    ${TENANT_ID_1}

TC_MEC_MEC048_MEO_CSE_008_NF
    [Documentation]    TP_MEC_MEC048_MEO_CSE_008_NF
    ...    Check that the IUT returns an error on creating the resourceQuotaInfo for a not existing tenant when requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.5.3.4, clause 6.2.3
    [Tags]    PIC_SERVICES
    Register resource quota Info   ${NOT_EXISTING_TENANT_ID}    ResourceQuotaInfo
    Check HTTP Response Status Code Is    404

# MISATKE IN URL (TEST PURPOSE) ,TO DO
TC_MEC_MEC048_MEO_CSE_009_OK
    [Documentation]    TP_MEC_MEC048_MEO_CSE_009_OK
    ...    Check that the IUT returns the list of per site resource quota for a specific tenant when requested to a CSE - No filter
    ...    ETSI GS MEC 048 v3.1.1, clause 7.6.3.1, clause 6.2.4
    [Tags]    PIC_SERVICES
    [Setup]   Register tenant Info    TenantInfo
    Register mutiple site resource quota Info and get site Ids    ${TENANT_ID_1}    SiteResourceQuotaInfo    SiteResourceQuotaInfo2    SiteResourceQuotaInfo3
    Retrieve all resource quota info resource   ${TENANT_ID_1} 
    Check HTTP Response Status Code Is    200
    Check HTTP Response Body Json Schema Is  SiteResourceQuotaInfoList
    FOR  ${element}  IN  @{response['body']}
      Should Be Equal As Strings    ${element}[siteId]      ${SITE_ID_1}
    END
    Remove mutiple site resource quota Info    ${TENANT_ID_1}    ${SITE_ID_1}    ${SITE_ID_2}    ${SITE_ID_3}
    [Teardown]  Remove specific tenant info resource    ${TENANT_ID_1}

TC_MEC_MEC048_MEO_CSE_009_OK_01
    [Documentation]    TP_MEC_MEC048_MEO_CSE_009_OK_01
    ...    Check that the IUT returns the list of per site resource quota for a specific tenant when requested to a CSE - siteId filter
    ...    ETSI GS MEC 048 v3.1.1, clause 7.6.3.1, clause 6.2.4
    [Tags]    PIC_SERVICES
    [Setup]   Register tenant Info    TenantInfo
    Register mutiple site resource quota Info and get site Ids    ${TENANT_ID_1}    SiteResourceQuotaInfo    SiteResourceQuotaInfo2    SKIP
    Retrieve all site resource quota info resource with query parameters   ${TENANT_ID_1}    siteId=${SITE_ID_1}
    Check HTTP Response Status Code Is    200
    Check HTTP Response Body Json Schema Is  SiteResourceQuotaInfoList
    FOR  ${element}  IN  @{response['body']}
      Should Be Equal As Strings    ${element}[siteId]      ${SITE_ID_1}
    END
    Remove mutiple site resource quota Info    ${TENANT_ID_1}    ${SITE_ID_1}    ${SITE_ID_2}    SKIP
    [Teardown]  Remove specific tenant info resource    ${TENANT_ID_1}

TC_MEC_MEC048_MEO_CSE_009_NF
    [Documentation]    TP_MEC_MEC048_MEO_CSE_009_NF
    ...    Check that the IUT returns an error on requesting site resource quota info on a not existing tenant when requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.6.3.1, clause 6.2.4
    [Tags]    PIC_SERVICES
    Retrieve all site resource quota info resource    ${NOT_EXISTING_TENANT_ID}
    Check HTTP Response Status Code Is    404

TC_MEC_MEC048_MEO_CSE_010_OK
    [Documentation]    TP_MEC_MEC048_MEO_CSE_010_OK
    ...    Check that the IUT creates a site resource quota info for an existing tenant when requested to a CSE
    ...    ETSI GS MEC 048 v3.1.1, clause 7.6.3.4, clause 6.2.4
    [Tags]    PIC_SERVICES
    [Setup]   Register tenant Info    TenantInfo
    Register site resource quota Info    ${TENANT_ID_1}    SiteResourceQuotaInfo
    Check HTTP Response Status Code Is    201
    Check HTTP Response Body Json Schema Is  SiteResourceQuotaInfo
    Remove specific site resource quota info resource    ${TENANT_ID_1}    ${response}[body][siteId]
    [Teardown]  Remove specific tenant info resource    ${TENANT_ID_1}

*** Keywords ***

Retrieve all tenant info resources
    Log    Getting all Tenant Info
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"*/*"}
    Set Headers    {"Authorization":"${TOKEN}"}
    Get    ${apiRoot}/${apiName}/${apiVersion}/tenants    
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}

Retrieve specific tenant info resource
    [Arguments]     ${TEANNT_ID}
    Log    Getting Specific Tenant Info Resource
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"*/*"}
    Set Headers    {"Authorization":"${TOKEN}"}
    GET    ${apiRoot}/${apiName}/${apiVersion}/tenants/${TEANNT_ID}
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}

Retrieve all tenant info resources with query parameters
    [Arguments]     ${query_params}
    Log    Getting all Tenant Info with query parameter
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"*/*"}
    Set Headers    {"Authorization":"${TOKEN}"}
    GET    ${apiRoot}/${apiName}/${apiVersion}/tenants?${query_params}
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}

Register tenant Info
    [Arguments]     ${content}
    Should Be True    ${PIC_MEC_PLAT} == 1
    Should Be True    ${PIC_SERVICES} == 1
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"application/json"}
    Set Headers    {"Authorization":"${TOKEN}"}
    ${file}=    Catenate    SEPARATOR=    jsons/    ${content}    .json
    ${body}=    Get File    ${file}
    POST   ${apiRoot}/${apiName}/${apiVersion}/tenants   ${body}
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}
    Set Suite Variable      ${TENANT_ID_1}    ${response}[body][tenantId]

Update tenant Info
    [Arguments]     ${tenantId}    ${content}
    Should Be True    ${PIC_MEC_PLAT} == 1
    Should Be True    ${PIC_SERVICES} == 1
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"application/json"}
    Set Headers    {"Authorization":"${TOKEN}"}
    ${file}=    Catenate    SEPARATOR=    jsons/    ${content}    .json
    ${body}=    Get File    ${file}
    PUT   ${apiRoot}/${apiName}/${apiVersion}/tenants/${tenantId}
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}
    Set Suite Variable      ${TENANT_ID}    ${response}[body][tenantId]

Update resource quota Info
    [Arguments]     ${tenantId}    ${content}
    Should Be True    ${PIC_MEC_PLAT} == 1
    Should Be True    ${PIC_SERVICES} == 1
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"application/json"}
    Set Headers    {"Authorization":"${TOKEN}"}
    ${file}=    Catenate    SEPARATOR=    jsons/    ${content}    .json
    ${body}=    Get File    ${file}
    PUT   ${apiRoot}/${apiName}/${apiVersion}/tenants/${tenantId}/resources/quota_in_system
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}
    Set Suite Variable      ${TENANT_ID}    ${response}[body][tenantId]

Register mutiple tenant Info and get tenant Ids
    [Arguments]     ${content_01}     ${content_02}    ${content_03}
    Register tenant Info    ${content_01}
    Set Suite Variable      ${TENANT_ID_1}    ${response}[body][tenantId]
    Set Suite Variable      ${CUSTOMER_ID_1}    ${response}[body][customerId]
    Set Suite Variable      ${CUSTOMER_NAME_1}    ${response}[body][customerName]
    Register tenant Info    ${content_02}
    Set Suite Variable      ${TENANT_ID_2}    ${response}[body][tenantId]
    Set Suite Variable      ${CUSTOMER_ID_2}    ${response}[body][customerId]
    Set Suite Variable      ${CUSTOMER_NAME_2}    ${response}[body][customerName]
    Register tenant Info    ${content_03}
    Set Suite Variable      ${TENANT_ID_3}    ${response}[body][tenantId]
    Set Suite Variable      ${CUSTOMER_ID_3}    ${response}[body][customerId]
    Set Suite Variable      ${CUSTOMER_NAME_3}    ${response}[body][customerName]

Remove mutiple tenant Info
    [Arguments]     ${tenant_id_1}   ${tenant_id_2}    ${tenant_id_3}    
    Run Keyword If    '${tenant_id_1}' != 'SKIP'    Remove specific tenant info resource   ${tenant_id_1} 
    Remove specific tenant info resource   ${tenant_id_2} 
    Remove specific tenant info resource   ${tenant_id_3}

Remove specific tenant info resource 
    [Arguments]     ${tenantId} 
    Should Be True    ${PIC_MEC_PLAT} == 1
    Should Be True    ${PIC_SERVICES} == 1
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"application/json"}
    DELETE  ${apiRoot}/${apiName}/${apiVersion}/tenants/${tenantId}
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output} 

Retrieve specific resource quota info resource
    [Arguments]     ${TEANNT_ID}
    Log    Getting Specific Resource Quota Info
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"*/*"}
    Set Headers    {"Authorization":"${TOKEN}"}
    GET    ${apiRoot}/${apiName}/${apiVersion}/tenants/${TEANNT_ID}/resources/quota_in_system 
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}

Retrieve all resource quota info resource
    [Arguments]     ${TEANNT_ID}
    Log    Getting All Resource Quota Info
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"*/*"}
    Set Headers    {"Authorization":"${TOKEN}"}
    GET    ${apiRoot}/${apiName}/${apiVersion}/tenants/${TEANNT_ID}/resources/quota_in_system 
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}

Retrieve all site resource quota info resource
    [Arguments]     ${TEANNT_ID}
    Log    Getting All Site Resource Quota Info
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"*/*"}
    Set Headers    {"Authorization":"${TOKEN}"}
    GET    ${apiRoot}/${apiName}/${apiVersion}/tenants/${TEANNT_ID}/resources/quota_in_sites 
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}

Retrieve all site resource quota info resource with query parameters
    [Arguments]     ${TEANNT_ID}    ${query_params}
    Log    Getting All Site Resource Quota Info with query parameters
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"*/*"}
    Set Headers    {"Authorization":"${TOKEN}"}
    GET    ${apiRoot}/${apiName}/${apiVersion}/tenants/${TEANNT_ID}/resources/quota_in_sites?${query_params}
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}

Register mutiple site resource quota Info and get site Ids
    [Arguments]     ${tenantId}    ${content_01}     ${content_02}    ${content_03}
    Register site resource quota Info    ${tenantId}    ${content_01}
    Set Suite Variable      ${SITE_ID_1}    ${response}[body][siteId]
    Register site resource quota Info    ${tenantId}    ${content_02}
    Set Suite Variable      ${SITE_ID_2}    ${response}[body][siteId]
    Run Keyword If    '${content_03}' != 'SKIP'    Register site resource quota Info    ${tenantId}    ${content_03}
    Run Keyword If    '${content_03}' != 'SKIP'    Set Suite Variable      ${SITE_ID_3}    ${response}[body][siteId]

Register resource quota Info
    [Arguments]     ${tenantId}    ${content}
    Should Be True    ${PIC_MEC_PLAT} == 1
    Should Be True    ${PIC_SERVICES} == 1
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"application/json"}
    Set Headers    {"Authorization":"${TOKEN}"}
    ${file}=    Catenate    SEPARATOR=    jsons/    ${content}    .json
    ${body}=    Get File    ${file}
    POST   ${apiRoot}/${apiName}/${apiVersion}/tenants/${tenantId}/resources/quota_in_system   ${body}
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}

Register site resource quota Info
    [Arguments]     ${tenantId}    ${content}
    Should Be True    ${PIC_MEC_PLAT} == 1
    Should Be True    ${PIC_SERVICES} == 1
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"application/json"}
    Set Headers    {"Authorization":"${TOKEN}"}
    ${file}=    Catenate    SEPARATOR=    jsons/    ${content}    .json
    ${body}=    Get File    ${file}
    POST   ${apiRoot}/${apiName}/${apiVersion}/tenants/${tenantId}/resources/quota_in_sites   ${body}
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}

Remove mutiple site resource quota Info
    [Arguments]     ${tenant_id_1}   ${site_id_1}    ${site_id_2}    ${site_id_3}    
    Run Keyword If    '${tenant_id_1}' != 'SKIP'    Remove specific site resource quota info resource   ${tenant_id_1}    ${site_id_1}
    Remove specific site resource quota info resource   ${tenant_id_1}    ${site_id_2}
    Run Keyword If    '${site_id_3}' != 'SKIP'    Remove specific site resource quota info resource   ${tenant_id_1}    ${site_id_3}

Remove specific resource quota info resource 
    [Arguments]     ${tenantId} 
    Should Be True    ${PIC_MEC_PLAT} == 1
    Should Be True    ${PIC_SERVICES} == 1
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"application/json"}
    DELETE  ${apiRoot}/${apiName}/${apiVersion}/tenants/${tenantId}/resources/quota_in_system
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}

Remove specific site resource quota info resource 
    [Arguments]     ${tenantId}    ${siteId}
    Should Be True    ${PIC_MEC_PLAT} == 1
    Should Be True    ${PIC_SERVICES} == 1
    Set Headers    {"Accept":"application/json"}
    Set Headers    {"Content-Type":"application/json"}
    DELETE  ${apiRoot}/${apiName}/${apiVersion}/tenants/${tenantId}/resources/quota_in_sites/${siteId}
    ${output}=    Output    response
    Set Suite Variable    ${response}    ${output}